### ISSUE TITLE
Fatel error in /vendor/composer/autoload_real.php on line 43

### ISSUE THREAD

**Issue by hamidabbaszadeh** [cyberspectrum/contao-toolbox#20]
This is output of crb.phar:

PHP Warning:  require(phar:///opt/contao-toolbox/ctb.phar/vendor/composer/autoload_files.php): failed to open stream: phar error: "vendor/composer/autoload_files.php" is not a file in phar "/opt/contao-toolbox/ctb.phar" in phar:///opt/contao-toolbox/ctb.phar/vendor/composer/autoload_real.php on line 43
PHP Fatal error:  require(): Failed opening required 'phar:///opt/contao-toolbox/ctb.phar/vendor/composer/autoload_files.php' (include_path='.:/usr/share/pear:/usr/share/php') in phar:///opt/contao-toolbox/ctb.phar/vendor/composer/

php version is 7.

**Comment by discordier** [comment]
Please check with 0.7.1

**Comment by hamidabbaszadeh** [comment]
:+1: Thanks, It works.
