### ISSUE TITLE
Running toolbox with PHP 7.2

### ISSUE THREAD

**Issue by dmolineus** [cyberspectrum/contao-toolbox#22]
Using Toolbox with 7.2 an `ErrorException` is from when calling `to-xliff`. It's caused by the following line, because `$matches[0]` does not contain an countable content.

https://github.com/cyberspectrum/contao-toolbox/blob/cc5a62958e2b757c527ab5d5b543ff71a90c5a18/src/CyberSpectrum/Translation/Contao/ContaoFile.php#L262

The condition should be changed to `$matches && strlen($matches[0]) > 0` or `$matches && count($matches)`.

**Comment by discordier** [comment]
`!empty($matches) && strlen($matches[0]) > 0` seems more logical to me.
I think we should add the default header always when no (non empty) header has been added, what do you think?

**Comment by discordier** [comment]
Fixed in upcoming version.
